name: test_tox

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Setup Poetry
        run: pip3 install poetry poetry-dynamic-versioning

      - name: Check Poetry
        run: poetry --version

      - name: Config Poetry for Cache
        if: ${{ !env.ACT }}
        run: poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        if: ${{ !env.ACT }}
        uses: actions/cache@v2.1.6
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-v0-${{ hashFiles('**/poetry.lock') }}

      - name: Install via Poetry
        run: poetry install --no-root --no-dev

      - name: Run Tox
        run: poetry run tox4
